{
  "build": "py310hca03da5_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/osx-arm64",
  "constrains": [],
  "depends": [
    "python >=3.10,<3.11.0a0"
  ],
  "extracted_package_dir": "/opt/anaconda3/pkgs/exceptiongroup-1.2.0-py310hca03da5_0",
  "files": [
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/INSTALLER",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/LICENSE",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/METADATA",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/RECORD",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/REQUESTED",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/WHEEL",
    "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/direct_url.json",
    "lib/python3.10/site-packages/exceptiongroup/__init__.py",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/__init__.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/_catch.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/_formatting.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/_suppress.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/__pycache__/_version.cpython-310.pyc",
    "lib/python3.10/site-packages/exceptiongroup/_catch.py",
    "lib/python3.10/site-packages/exceptiongroup/_exceptions.py",
    "lib/python3.10/site-packages/exceptiongroup/_formatting.py",
    "lib/python3.10/site-packages/exceptiongroup/_suppress.py",
    "lib/python3.10/site-packages/exceptiongroup/_version.py",
    "lib/python3.10/site-packages/exceptiongroup/py.typed"
  ],
  "fn": "exceptiongroup-1.2.0-py310hca03da5_0.conda",
  "license": "MIT",
  "link": {
    "source": "/opt/anaconda3/pkgs/exceptiongroup-1.2.0-py310hca03da5_0",
    "type": 1
  },
  "md5": "98ff1ba4d5447dda99f3cb3086c6b37b",
  "name": "exceptiongroup",
  "package_tarball_full_path": "/opt/anaconda3/pkgs/exceptiongroup-1.2.0-py310hca03da5_0.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/LICENSE",
        "path_type": "hardlink",
        "sha256": "6e5070d765031e0ad403a1cbf90ae6d19a0228f802e320b7acff460aa72ed47c",
        "sha256_in_prefix": "6e5070d765031e0ad403a1cbf90ae6d19a0228f802e320b7acff460aa72ed47c",
        "size_in_bytes": 3704
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "1d998cf5f14e54cf261360d854a049606682f73813b6a22d1b1d7bd51f17ba2e",
        "sha256_in_prefix": "1d998cf5f14e54cf261360d854a049606682f73813b6a22d1b1d7bd51f17ba2e",
        "size_in_bytes": 6603
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "95c5944b956bc95b587c46fce482c99da24a6b6a7866db5f3feb9067ba7f5fd2",
        "sha256_in_prefix": "95c5944b956bc95b587c46fce482c99da24a6b6a7866db5f3feb9067ba7f5fd2",
        "size_in_bytes": 1542
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/REQUESTED",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "1196c6921ec87b83e865f450f08d19b8ff5592537f4ef719e83484e546abe33e",
        "sha256_in_prefix": "1196c6921ec87b83e865f450f08d19b8ff5592537f4ef719e83484e546abe33e",
        "size_in_bytes": 81
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup-1.2.0.dist-info/direct_url.json",
        "path_type": "hardlink",
        "sha256": "466f04464c995efffcba898b356918a0b196a7b0e1f9ef0b2988dbfe7c34590c",
        "sha256_in_prefix": "466f04464c995efffcba898b356918a0b196a7b0e1f9ef0b2988dbfe7c34590c",
        "size_in_bytes": 145
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__init__.py",
        "path_type": "hardlink",
        "sha256": "ec31d2d210e4f9122cdc841cdd26d9541d3ed4c86248227d5e0bc4c849682fb3",
        "sha256_in_prefix": "ec31d2d210e4f9122cdc841cdd26d9541d3ed4c86248227d5e0bc4c849682fb3",
        "size_in_bytes": 1049
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/__init__.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "fe621b2c1dd131e83700b0bd50c1f9257f244a5e3bfd2db06db2bacd1de186ef",
        "sha256_in_prefix": "fe621b2c1dd131e83700b0bd50c1f9257f244a5e3bfd2db06db2bacd1de186ef",
        "size_in_bytes": 844
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/_catch.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "b4883f32c050a7a4619f9aa50a69fd473920590a9f9f728b8beda81144a64169",
        "sha256_in_prefix": "b4883f32c050a7a4619f9aa50a69fd473920590a9f9f728b8beda81144a64169",
        "size_in_bytes": 3230
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/_exceptions.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "7a6f80d8f7972d52ecbc6b1ac4379beb7d6fff28cd48c4d5e93f175c6f68c4f4",
        "sha256_in_prefix": "7a6f80d8f7972d52ecbc6b1ac4379beb7d6fff28cd48c4d5e93f175c6f68c4f4",
        "size_in_bytes": 9566
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/_formatting.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "0f38f7f82363e59f8d05173fd1df4e16387d790fb11be685ef669f98a4ad0940",
        "sha256_in_prefix": "0f38f7f82363e59f8d05173fd1df4e16387d790fb11be685ef669f98a4ad0940",
        "size_in_bytes": 12181
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/_suppress.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "2524b90ec4ac1b069acb0e9ed57e075e2106fa4fc4eef005f136a11d2b11da31",
        "sha256_in_prefix": "2524b90ec4ac1b069acb0e9ed57e075e2106fa4fc4eef005f136a11d2b11da31",
        "size_in_bytes": 1088
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/__pycache__/_version.cpython-310.pyc",
        "path_type": "hardlink",
        "sha256": "6785c0740e6e5a79377ec1880306b0675a9145d24f46b8e4d9c27bb1e0927c5e",
        "sha256_in_prefix": "6785c0740e6e5a79377ec1880306b0675a9145d24f46b8e4d9c27bb1e0927c5e",
        "size_in_bytes": 243
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/_catch.py",
        "path_type": "hardlink",
        "sha256": "926c74d4b904648e7ea66c61f404c43b8bf3a80b649fb9e357ee59f85d0aa7e2",
        "sha256_in_prefix": "926c74d4b904648e7ea66c61f404c43b8bf3a80b649fb9e357ee59f85d0aa7e2",
        "size_in_bytes": 4669
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/_exceptions.py",
        "path_type": "hardlink",
        "sha256": "7fe58e5c7c3e9555800198c663c73e285c687c2bc37049785de3037aa7203328",
        "sha256_in_prefix": "7fe58e5c7c3e9555800198c663c73e285c687c2bc37049785de3037aa7203328",
        "size_in_bytes": 11010
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/_formatting.py",
        "path_type": "hardlink",
        "sha256": "9ae98881193ad6d86fef03fa5b30a954db063e16191967df25e1b34278052f4b",
        "sha256_in_prefix": "9ae98881193ad6d86fef03fa5b30a954db063e16191967df25e1b34278052f4b",
        "size_in_bytes": 21005
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/_suppress.py",
        "path_type": "hardlink",
        "sha256": "f3298ac7900570ed79178ecd7e7448f86f7c9a7e19057bb2b78aa22dde730f74",
        "sha256_in_prefix": "f3298ac7900570ed79178ecd7e7448f86f7c9a7e19057bb2b78aa22dde730f74",
        "size_in_bytes": 1338
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/_version.py",
        "path_type": "hardlink",
        "sha256": "0a29461f271247399212708c42f4d127927f2d6c4cb3efbe52a9156ce990dab0",
        "sha256_in_prefix": "0a29461f271247399212708c42f4d127927f2d6c4cb3efbe52a9156ce990dab0",
        "size_in_bytes": 160
      },
      {
        "_path": "lib/python3.10/site-packages/exceptiongroup/py.typed",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "3a7ccda756744dd070806d1a9fe6101b171d991ea50172c763d229299b73be5b",
  "size": 31405,
  "subdir": "osx-arm64",
  "timestamp": 1706031457000,
  "url": "https://repo.anaconda.com/pkgs/main/osx-arm64/exceptiongroup-1.2.0-py310hca03da5_0.conda",
  "version": "1.2.0"
}